### PR TITLE
Feature/11 configure network class

### PR DESCRIPTION
**Pull request by Mumthasir-vp**

### CODE REVIEW

**Review by georgepadayatti — APPROVED** [review]

**Comment by georgepadayatti** [comment]
@Mumthasir-vp Small comment: Please make sure the commit messages are formatted correct from next time onwards.

**Comment by Mumthasir-vp** [comment]
@georgepadayatti  You meant commit message should be descriptive, right ?

**Comment by georgepadayatti** [comment]
> @georgepadayatti  You meant commit message should be descriptive, right ?

No. I meant the formatting in this case. The # should appear as prefix to issue number not at the start of commit message.

**Comment by Mumthasir-vp** [comment]
Oh got it. Sorry for the mistake.

**Comment by georgepadayatti** [comment]
> Oh got it. Sorry for the mistake.

nw

**Pull request merged**
